//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PIV.PIV_WS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="webscraping_WSPortBinding", Namespace="http://elementos.webscraping_ws.web.br/")]
    public partial class webscraping_WS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback tagOperationCompleted;
        
        private System.Threading.SendOrPostCallback copa_selectOperationCompleted;
        
        private System.Threading.SendOrPostCallback feednewsOperationCompleted;
        
        private System.Threading.SendOrPostCallback tabelabrOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public webscraping_WS() {
            this.Url = global::PIV.Properties.Settings.Default.PIV_PIV_WS_webscraping_WS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event tagCompletedEventHandler tagCompleted;
        
        /// <remarks/>
        public event copa_selectCompletedEventHandler copa_selectCompleted;
        
        /// <remarks/>
        public event feednewsCompletedEventHandler feednewsCompleted;
        
        /// <remarks/>
        public event tabelabrCompletedEventHandler tabelabrCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://elementos.webscraping_ws.web.br/", ResponseNamespace="http://elementos.webscraping_ws.web.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool tag([System.Xml.Serialization.XmlElementAttribute("tag", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tag1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int page_i) {
            object[] results = this.Invoke("tag", new object[] {
                        tag1,
                        page_i});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void tagAsync(string tag1, int page_i) {
            this.tagAsync(tag1, page_i, null);
        }
        
        /// <remarks/>
        public void tagAsync(string tag1, int page_i, object userState) {
            if ((this.tagOperationCompleted == null)) {
                this.tagOperationCompleted = new System.Threading.SendOrPostCallback(this.OntagOperationCompleted);
            }
            this.InvokeAsync("tag", new object[] {
                        tag1,
                        page_i}, this.tagOperationCompleted, userState);
        }
        
        private void OntagOperationCompleted(object arg) {
            if ((this.tagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tagCompleted(this, new tagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://elementos.webscraping_ws.web.br/", ResponseNamespace="http://elementos.webscraping_ws.web.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool copa_select([System.Xml.Serialization.XmlElementAttribute("copa_select", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string copa_select1) {
            object[] results = this.Invoke("copa_select", new object[] {
                        copa_select1});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void copa_selectAsync(string copa_select1) {
            this.copa_selectAsync(copa_select1, null);
        }
        
        /// <remarks/>
        public void copa_selectAsync(string copa_select1, object userState) {
            if ((this.copa_selectOperationCompleted == null)) {
                this.copa_selectOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncopa_selectOperationCompleted);
            }
            this.InvokeAsync("copa_select", new object[] {
                        copa_select1}, this.copa_selectOperationCompleted, userState);
        }
        
        private void Oncopa_selectOperationCompleted(object arg) {
            if ((this.copa_selectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.copa_selectCompleted(this, new copa_selectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://elementos.webscraping_ws.web.br/", ResponseNamespace="http://elementos.webscraping_ws.web.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool feednews([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int page_i) {
            object[] results = this.Invoke("feednews", new object[] {
                        page_i});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void feednewsAsync(int page_i) {
            this.feednewsAsync(page_i, null);
        }
        
        /// <remarks/>
        public void feednewsAsync(int page_i, object userState) {
            if ((this.feednewsOperationCompleted == null)) {
                this.feednewsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfeednewsOperationCompleted);
            }
            this.InvokeAsync("feednews", new object[] {
                        page_i}, this.feednewsOperationCompleted, userState);
        }
        
        private void OnfeednewsOperationCompleted(object arg) {
            if ((this.feednewsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.feednewsCompleted(this, new feednewsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://elementos.webscraping_ws.web.br/", ResponseNamespace="http://elementos.webscraping_ws.web.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool tabelabr([System.Xml.Serialization.XmlElementAttribute("tabelabr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tabelabr1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int ano) {
            object[] results = this.Invoke("tabelabr", new object[] {
                        tabelabr1,
                        ano});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void tabelabrAsync(string tabelabr1, int ano) {
            this.tabelabrAsync(tabelabr1, ano, null);
        }
        
        /// <remarks/>
        public void tabelabrAsync(string tabelabr1, int ano, object userState) {
            if ((this.tabelabrOperationCompleted == null)) {
                this.tabelabrOperationCompleted = new System.Threading.SendOrPostCallback(this.OntabelabrOperationCompleted);
            }
            this.InvokeAsync("tabelabr", new object[] {
                        tabelabr1,
                        ano}, this.tabelabrOperationCompleted, userState);
        }
        
        private void OntabelabrOperationCompleted(object arg) {
            if ((this.tabelabrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tabelabrCompleted(this, new tabelabrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void tagCompletedEventHandler(object sender, tagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void copa_selectCompletedEventHandler(object sender, copa_selectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class copa_selectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal copa_selectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void feednewsCompletedEventHandler(object sender, feednewsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class feednewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal feednewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void tabelabrCompletedEventHandler(object sender, tabelabrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tabelabrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tabelabrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591